version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=rag_chat_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - API_KEY=your-secret-api-key-here
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - OPENAI_API_KEY=your-openai-api-key-here
      - OPENAI_MODEL=gpt-3.5-turbo
      - EMBEDDING_MODEL=text-embedding-ada-002
      - PINECONE_API_KEY=your-pinecone-api-key-here
      - PINECONE_ENVIRONMENT=your-pinecone-environment
      - PINECONE_INDEX=rag-documents
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rag_chat_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: